# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2b9abea166accde6c4da443154f19008fa7d10663f305c79e9077a83493c85fb7044a2ec681438fd3f4dd0c4e07352fd90a83e2eaeff8031b2d8abca9ce1ba7

test:
  secret_key_base: 57e155fcc7eb96fa65377bed0c7e5b651c35257cb3e88f6cdb52f46d2b0bc419532bdd0385821c108e92e4f5d97eb6a46612c9136a74c718f9b13d683a2aac0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
